config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :maps
resources :provinces

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  iso_code   :string(255)
#  created_at :datetime
#  updated_at :datetime
#  geom       :spatial          multipolygon, 4326
#

class Country < ActiveRecord::Base
  # self.rgeo_factory_generator = RGeo::Geos.factory_generator

end

app/models/province.rb
# == Schema Information
#
# Table name: provinces
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#  geom       :spatial          multipolygon, 4326
#

class Province < ActiveRecord::Base
  include Featurable

  featurable :geom, [:name]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def index
    
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController

  def index
      @provinces = Province.all

      respond_to do |format|
        format.json do  
          feature_collection = Province.to_feature_collection @provinces
          render json: RGeo::GeoJSON.encode(feature_collection)
        end

        format.html
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolPro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDB06c3JC9Puup5N4gk3cK1j9sQ0kO615U&sensor=false"></script>
    <style type="text/css">
      #mapDiv {
        width: 1200px;
        height: 800px;
      }
    </style>

    <script type="text/javascript">
      var map;
      function initMap() {
        google.maps.visualRefresh = true;

        var mapOptions = {
          zoom: 1,
          mapTypeControlOptions: {mapTypeIds:
               [google.maps.MapTypeId.ROADMAP]}
        };

        var mapElement = document.getElementById('mapDiv');
        map = new google.maps.Map(mapElement, mapOptions);
        map.setMapTypeId(google.maps.MapTypeId.ROADMAP);

        //Load GeoJSON
        map.data.loadGeoJson("/gabon.json");

        zoomToIstanbul();
      }

      function zoomToIstanbul() {
        var istanbul = new google.maps.LatLng(41.0579, 29.0340);
        map.setCenter(istanbul);
      }

      function zoomToStreet() {
        map.setZoom(18);
      }

      function disableDrag() {
        map.setOptions({draggable: false});
      }

      function setMaxZoom() {
        map.setOptions({maxZoom: 12});
      }

      function setMinZoom() {
        map.setOptions({minZoom: 5});
      }

      function changeUI() {
        map.setOptions({disableDefaultUI: true});
      }

      function disableScroll() {
        map.setOptions({scrollwheel: false});
      }

      function startButtonEvents() {
        document.getElementById('btnZoomToIst')
                .addEventListener('click', function(){
                  zoomToIstanbul();
                });

        document.getElementById('btnZoomToStr')
              .addEventListener('click', function() {
                zoomToStreet();
              });

        document.getElementById('btnDisableDrag')
              .addEventListener('click', function(){
                disableDrag();
              });

        document.getElementById('btnMaxZoom')
              .addEventListener('click', function() {
                setMaxZoom();
              });
        document.getElementById('btnMinZoom')
              .addEventListener('click', function() {
                setMinZoom();
              });
        document.getElementById('btnChangeUI')
              .addEventListener('click', function() {
                changeUI();
              })
        document.getElementById('btnDisableScroll')
              .addEventListener('click', function() {
                disableScroll();
              });
      }

      google.maps.event.addDomListener(window, 'load', initMap);
      document.addEventListener('DOMContentLoaded', startButtonEvents);
    </script>
  </head>
  <body>
    <h1>My First Map</h1>
    <input id="btnZoomToIst" type="button" value="Zoom To Istanbul" />
    <input id="btnZoomToStr" type="button" value="Zoom To Street Level" />
    <input id="btnDisableDrag" type="button" value="Disable Drag" />
    <input id="btnMaxZoom" type="button" value="Set Max Zoom to 12" />
    <input id="btnMinZoom" type="button" value="Set Min Zoom to 5" />
    <input id="btnChangeUI" type="button" value="Change UI" />
    <input id="btnDisableScroll" type="button" value="Disable Scroll Zoom" />

    <div id="mapDiv"></div>
  </body>
</html>

app/views/provinces/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDB06c3JC9Puup5N4gk3cK1j9sQ0kO615U&sensor=false"></script>
    <style type="text/css">
      #mapDiv {
        width: 1200px;
        height: 800px;
      }

    </style>

    <script type="text/javascript">
      var map;
      function initMap() {
        google.maps.visualRefresh = true;

        var mapOptions = {
          zoom: 1,
          mapTypeControlOptions: {mapTypeIds:
               [google.maps.MapTypeId.ROADMAP]}
        };

        var mapElement = document.getElementById('mapDiv');
        map = new google.maps.Map(mapElement, mapOptions);
        map.setMapTypeId(google.maps.MapTypeId.ROADMAP);
        
        //Load GeoJSON
        map.data.loadGeoJson("<%= provinces_path format: :json -%>");
        
        map.setZoom(7);
        var gabon = new google.maps.LatLng(1.000000, 11.45000000);
        map.setCenter(gabon);

        //Create an info box for displaying names
        var infoBox = document.createElement('div');
        infoBox.innerHTML = "<div id='info-box'></div>";
        map.controls[google.maps.ControlPosition.RIGHT_TOP].push(infoBox);

        map.data.addListener('mouseover', function(event) {
          map.data.revertStyle();
          $('#info-box').text(event.feature.getProperty('name'));
          map.data.overrideStyle(event.feature, { fillColor: 'red' });


        });

        map.data.addListener('mouseout', function(event){
          map.data.revertStyle();
        });

        map.data.setStyle(function(feature) {
          return { fillColor: 'green',
                  strokeWeight: 1}
        });


      }

      function zoomToIstanbul() {
        var istanbul = new google.maps.LatLng(41.0579, 29.0340);
        map.setCenter(istanbul);
      }

      function zoomToStreet() {
        map.setZoom(18);
      }

      function disableDrag() {
        map.setOptions({draggable: false});
      }

      function setMaxZoom() {
        map.setOptions({maxZoom: 12});
      }

      function setMinZoom() {
        map.setOptions({minZoom: 5});
      }

      function changeUI() {
        map.setOptions({disableDefaultUI: true});
      }

      function disableScroll() {
        map.setOptions({scrollwheel: false});
      }

      function startButtonEvents() {
        document.getElementById('btnZoomToIst')
                .addEventListener('click', function(){
                  zoomToIstanbul();
                });

        document.getElementById('btnZoomToStr')
              .addEventListener('click', function() {
                zoomToStreet();
              });

        document.getElementById('btnDisableDrag')
              .addEventListener('click', function(){
                disableDrag();
              });

        document.getElementById('btnMaxZoom')
              .addEventListener('click', function() {
                setMaxZoom();
              });
        document.getElementById('btnMinZoom')
              .addEventListener('click', function() {
                setMinZoom();
              });
        document.getElementById('btnChangeUI')
              .addEventListener('click', function() {
                changeUI();
              })
        document.getElementById('btnDisableScroll')
              .addEventListener('click', function() {
                disableScroll();
              });
      }

      google.maps.event.addDomListener(window, 'load', initMap);
      document.addEventListener('DOMContentLoaded', startButtonEvents);
    </script>
  </head>
  <body>
    <h1>My First Map</h1>
    <input id="btnZoomToIst" type="button" value="Zoom To Istanbul" />
    <input id="btnZoomToStr" type="button" value="Zoom To Street Level" />
    <input id="btnDisableDrag" type="button" value="Disable Drag" />
    <input id="btnMaxZoom" type="button" value="Set Max Zoom to 12" />
    <input id="btnMinZoom" type="button" value="Set Min Zoom to 5" />
    <input id="btnChangeUI" type="button" value="Change UI" />
    <input id="btnDisableScroll" type="button" value="Disable Scroll Zoom" />

    <div id="mapDiv"></div>
  </body>
</html>